use DBQuizzes
go

insert into UserAccount values	('Pero','PeroPeric@mail.hr','PeroPSW'),
							('Maja','MajaMajic@mail.hr','MajaPSW'),
							('Iva','IvaIvic@mail.hr','IvaPSW'),
							('Luka','LukaLukic@mail.hr','LukaPSW')

Insert into QuizType values ('Edukacija'),
						('Zabava')

Insert into Quiz (Title, QuizTypeID, UserAccountID) values ('Kviz 1', (select IDQuizType from QuizType where QuizType = 'Edukacija'), (select IDUserAccount from UserAccount where UserName = 'Pero')),
						('Kviz 2', (select IDQuizType from QuizType where QuizType = 'Zabava'), (select IDUserAccount from UserAccount where UserName = 'Pero')),
						('Kviz 3', (select IDQuizType from QuizType where QuizType = 'Zabava'), (select IDUserAccount from UserAccount where UserName = 'Maja')),
						('Kviz 4', (select IDQuizType from QuizType where QuizType = 'Edukacija'), (select IDUserAccount from UserAccount where UserName = 'Pero')),
						('Kviz 5', (select IDQuizType from QuizType where QuizType = 'Edukacija'), (select IDUserAccount from UserAccount where UserName = 'Iva')),
						('Kviz 6', (select IDQuizType from QuizType where QuizType = 'Zabava'), (select IDUserAccount from UserAccount where UserName = 'Luka')),
						('Kviz 7', (select IDQuizType from QuizType where QuizType = 'Edukacija'), (select IDUserAccount from UserAccount where UserName = 'Maja')),
						('Kviz 8', (select IDQuizType from QuizType where QuizType = 'Zabava'), (select IDUserAccount from UserAccount where UserName = 'Pero'))

Insert into Question values ('Kviz 1, pitanje 1?', 15,  5, (select IDQuiz from Quiz where Title = 'Kviz 1')),
							('Kviz 1, pitanje 2?', 5 , 2, (select IDQuiz from Quiz where Title = 'Kviz 1')),
							('Kviz 1, pitanje 3?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 1')),
							('Kviz 1, pitanje 4?', 9,  3, (select IDQuiz from Quiz where Title = 'Kviz 1')),
							('Kviz 1, pitanje 5?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 1')),
							('Kviz 2, pitanje 1?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 2')),
							('Kviz 2, pitanje 2?', 10, 4, (select IDQuiz from Quiz where Title = 'Kviz 2')),
							('Kviz 2, pitanje 3?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 2')),
							('Kviz 2, pitanje 4?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 2')),
							('Kviz 2, pitanje 5?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 2')),
							('Kviz 3, pitanje 1?', 9,  4, (select IDQuiz from Quiz where Title = 'Kviz 3')),
							('Kviz 3, pitanje 2?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 3')),
							('Kviz 3, pitanje 3?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 3')),
							('Kviz 3, pitanje 4?', 13, 5, (select IDQuiz from Quiz where Title = 'Kviz 3')),
							('Kviz 3, pitanje 5?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 3')),
							('Kviz 4, pitanje 1?', 11, 4, (select IDQuiz from Quiz where Title = 'Kviz 4')),
							('Kviz 4, pitanje 2?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 4')),
							('Kviz 4, pitanje 3?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 4')),
							('Kviz 4, pitanje 4?', 8,  3, (select IDQuiz from Quiz where Title = 'Kviz 4')),
							('Kviz 4, pitanje 5?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 4')),
							('Kviz 5, pitanje 1?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 5')),
							('Kviz 5, pitanje 2?', 8,  3, (select IDQuiz from Quiz where Title = 'Kviz 5')),
							('Kviz 5, pitanje 3?', 11, 4, (select IDQuiz from Quiz where Title = 'Kviz 5')),
							('Kviz 5, pitanje 4?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 5')),
							('Kviz 5, pitanje 5?', 12, 4, (select IDQuiz from Quiz where Title = 'Kviz 5')),
							('Kviz 6, pitanje 1?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 6')),
							('Kviz 6, pitanje 2?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 6')),
							('Kviz 6, pitanje 3?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 6')),
							('Kviz 6, pitanje 4?', 11, 4, (select IDQuiz from Quiz where Title = 'Kviz 6')),
							('Kviz 6, pitanje 5?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 6')),
							('Kviz 7, pitanje 1?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 7')),
							('Kviz 7, pitanje 2?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 7')),
							('Kviz 7, pitanje 3?', 11, 4, (select IDQuiz from Quiz where Title = 'Kviz 7')),
							('Kviz 7, pitanje 4?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 7')),
							('Kviz 7, pitanje 5?', 10, 4, (select IDQuiz from Quiz where Title = 'Kviz 7')),
							('Kviz 8, pitanje 1?', 7,  3, (select IDQuiz from Quiz where Title = 'Kviz 8')),
							('Kviz 8, pitanje 2?', 15, 5, (select IDQuiz from Quiz where Title = 'Kviz 8')),
							('Kviz 8, pitanje 3?', 10, 4, (select IDQuiz from Quiz where Title = 'Kviz 8')),
							('Kviz 8, pitanje 4?', 5,  2, (select IDQuiz from Quiz where Title = 'Kviz 8')),
							('Kviz 8, pitanje 5?', 8,  3, (select IDQuiz from Quiz where Title = 'Kviz 8'))


insert into Answer values   ('Kviz 1, pitanje 1, odgovor 1', 1, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 1?')),
							('Kviz 1, pitanje 1, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 1?')),
							('Kviz 1, pitanje 1, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 1?')),
							('Kviz 1, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 1?')),
							('Kviz 1, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 2?')),
							('Kviz 1, pitanje 2, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 2?')),
							('Kviz 1, pitanje 2, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 2?')),
							('Kviz 1, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 2?')),
							('Kviz 1, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 3?')),
							('Kviz 1, pitanje 3, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 3?')),
							('Kviz 1, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 3?')),
							('Kviz 1, pitanje 3, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 3?')),
							('Kviz 1, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 4?')),
							('Kviz 1, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 4?')),
							('Kviz 1, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 4?')),
							('Kviz 1, pitanje 4, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 4?')),
							('Kviz 1, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 5?')),
							('Kviz 1, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 5?')),
							('Kviz 1, pitanje 5, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 5?')),
							('Kviz 1, pitanje 5, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 1, pitanje 5?')),
																	
							('Kviz 2, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 1?')),
							('Kviz 2, pitanje 1, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 1?')),
							('Kviz 2, pitanje 1, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 1?')),
							('Kviz 2, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 1?')),
							('Kviz 2, pitanje 2, odgovor 1', 1, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 2?')),
							('Kviz 2, pitanje 2, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 2?')),
							('Kviz 2, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 2?')),
							('Kviz 2, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 2?')),
							('Kviz 2, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 3?')),
							('Kviz 2, pitanje 3, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 3?')),
							('Kviz 2, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 3?')),
							('Kviz 2, pitanje 3, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 3?')),
							('Kviz 2, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 4?')),
							('Kviz 2, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 4?')),
							('Kviz 2, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 4?')),
							('Kviz 2, pitanje 4, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 4?')),
							('Kviz 2, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 5?')),
							('Kviz 2, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 5?')),
							('Kviz 2, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 5?')),
							('Kviz 2, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 2, pitanje 5?')),
															
							('Kviz 3, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 1?')),
							('Kviz 3, pitanje 1, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 1?')),
							('Kviz 3, pitanje 1, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 1?')),
							('Kviz 3, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 1?')),
							('Kviz 3, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 2?')),
							('Kviz 3, pitanje 2, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 2?')),
							('Kviz 3, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 2?')),
							('Kviz 3, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 2?')),
							('Kviz 3, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 3?')),
							('Kviz 3, pitanje 3, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 3?')),
							('Kviz 3, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 3?')),
							('Kviz 3, pitanje 3, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 3?')),
							('Kviz 3, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 4?')),
							('Kviz 3, pitanje 4, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 4?')),
							('Kviz 3, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 4?')),
							('Kviz 3, pitanje 4, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 4?')),
							('Kviz 3, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 5?')),
							('Kviz 3, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 5?')),
							('Kviz 3, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 5?')),
							('Kviz 3, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 3, pitanje 5?')),
																
							('Kviz 4, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 1?')),
							('Kviz 4, pitanje 1, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 1?')),
							('Kviz 4, pitanje 1, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 1?')),
							('Kviz 4, pitanje 1, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 1?')),
							('Kviz 4, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 2?')),
							('Kviz 4, pitanje 2, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 2?')),
							('Kviz 4, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 2?')),
							('Kviz 4, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 2?')),
							('Kviz 4, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 3?')),
							('Kviz 4, pitanje 3, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 3?')),
							('Kviz 4, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 3?')),
							('Kviz 4, pitanje 3, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 3?')),
							('Kviz 4, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 4?')),
							('Kviz 4, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 4?')),
							('Kviz 4, pitanje 4, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 4?')),
							('Kviz 4, pitanje 4, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 4?')),
							('Kviz 4, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 5?')),
							('Kviz 4, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 5?')),
							('Kviz 4, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 5?')),
							('Kviz 4, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 4, pitanje 5?')),
																	
							('Kviz 5, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 1?')),
							('Kviz 5, pitanje 1, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 1?')),
							('Kviz 5, pitanje 1, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 1?')),
							('Kviz 5, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 1?')),
							('Kviz 5, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 2?')),
							('Kviz 5, pitanje 2, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 2?')),
							('Kviz 5, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 2?')),
							('Kviz 5, pitanje 2, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 2?')),
							('Kviz 5, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 3?')),
							('Kviz 5, pitanje 3, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 3?')),
							('Kviz 5, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 3?')),
							('Kviz 5, pitanje 3, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 3?')),
							('Kviz 5, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 4?')),
							('Kviz 5, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 4?')),
							('Kviz 5, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 4?')),
							('Kviz 5, pitanje 4, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 4?')),
							('Kviz 5, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 5?')),
							('Kviz 5, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 5?')),
							('Kviz 5, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 5?')),
							('Kviz 5, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 5, pitanje 5?')),
																
							('Kviz 6, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 1?')),
							('Kviz 6, pitanje 1, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 1?')),
							('Kviz 6, pitanje 1, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 1?')),
							('Kviz 6, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 1?')),
							('Kviz 6, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 2?')),
							('Kviz 6, pitanje 2, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 2?')),
							('Kviz 6, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 2?')),
							('Kviz 6, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 2?')),
							('Kviz 6, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 3?')),
							('Kviz 6, pitanje 3, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 3?')),
							('Kviz 6, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 3?')),
							('Kviz 6, pitanje 3, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 3?')),
							('Kviz 6, pitanje 4, odgovor 1', 1, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 4?')),
							('Kviz 6, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 4?')),
							('Kviz 6, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 4?')),
							('Kviz 6, pitanje 4, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 4?')),
							('Kviz 6, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 5?')),
							('Kviz 6, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 5?')),
							('Kviz 6, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 5?')),
							('Kviz 6, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 6, pitanje 5?')),
																	
							('Kviz 7, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 1?')),
							('Kviz 7, pitanje 1, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 1?')),
							('Kviz 7, pitanje 1, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 1?')),
							('Kviz 7, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 1?')),
							('Kviz 7, pitanje 2, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 2?')),
							('Kviz 7, pitanje 2, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 2?')),
							('Kviz 7, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 2?')),
							('Kviz 7, pitanje 2, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 2?')),
							('Kviz 7, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 3?')),
							('Kviz 7, pitanje 3, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 3?')),
							('Kviz 7, pitanje 3, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 3?')),
							('Kviz 7, pitanje 3, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 3?')),
							('Kviz 7, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 4?')),
							('Kviz 7, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 4?')),
							('Kviz 7, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 4?')),
							('Kviz 7, pitanje 4, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 4?')),
							('Kviz 7, pitanje 5, odgovor 1', 1, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 5?')),
							('Kviz 7, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 5?')),
							('Kviz 7, pitanje 5, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 5?')),
							('Kviz 7, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 7, pitanje 5?')),
														
							('Kviz 8, pitanje 1, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 1?')),
							('Kviz 8, pitanje 1, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 1?')),
							('Kviz 8, pitanje 1, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 1?')),
							('Kviz 8, pitanje 1, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 1?')),
							('Kviz 8, pitanje 2, odgovor 1', 1, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 2?')),
							('Kviz 8, pitanje 2, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 2?')),
							('Kviz 8, pitanje 2, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 2?')),
							('Kviz 8, pitanje 2, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 2?')),
							('Kviz 8, pitanje 3, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 3?')),
							('Kviz 8, pitanje 3, odgovor 2', 1, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 3?')),
							('Kviz 8, pitanje 3, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 3?')),
							('Kviz 8, pitanje 3, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 3?')),
							('Kviz 8, pitanje 4, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 4?')),
							('Kviz 8, pitanje 4, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 4?')),
							('Kviz 8, pitanje 4, odgovor 3', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 4?')),
							('Kviz 8, pitanje 4, odgovor 4', 1, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 4?')),
							('Kviz 8, pitanje 5, odgovor 1', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 5?')),
							('Kviz 8, pitanje 5, odgovor 2', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 5?')),
							('Kviz 8, pitanje 5, odgovor 3', 1, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 5?')),
							('Kviz 8, pitanje 5, odgovor 4', 0, (select IDQuestion from Question where Question = 'Kviz 8, pitanje 5?'))


select * from UserAccount
select * from QuizType 
select * from Quiz
select * from Question
select * from Answer